apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: traces-test
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: traces-test-warehouse
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: gitopsRepo
          value: https://github.com/tijnsemmekrot/traces-test.git
        - name: branch
          value: kargo-implementation
        - name: registry
          value: 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566
      steps:
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitopsRepo }}
            checkout:
              - branch: ${{ vars.branch }}
                path: repo

        # Service 1: account-service
        - uses: kustomize-set-image
          as: update-account-service
          config:
            path: repo/environments/dev/account-service
            images:
              - image: ${{ vars.registry }}/traces-test-account-service
                # Use the image() function to fetch the tag for this specific URL
                newTag: ${{ image(vars.registry + '/traces-test-account-service').tag }}

        # Service 2: fraud-detector
        - uses: kustomize-set-image
          as: update-fraud-detector
          config:
            path: repo/environments/dev/fraud-detector
            images:
              - image: ${{ vars.registry }}/traces-test-fraud-detector
                newTag: ${{ image(vars.registry + '/traces-test-fraud-detector').tag }}

        # Service 3: notification-service
        - uses: kustomize-set-image
          as: update-notification-service
          config:
            path: repo/environments/dev/notification-service
            images:
              - image: ${{ vars.registry }}/traces-test-notification-service
                newTag: ${{ image(vars.registry + '/traces-test-notification-service').tag }}

        # Service 4: payment-processor
        - uses: kustomize-set-image
          as: update-payment-processor
          config:
            path: repo/environments/dev/payment-processor
            images:
              - image: ${{ vars.registry }}/traces-test-payment-processor
                newTag: ${{ image(vars.registry + '/traces-test-payment-processor').tag }}

        # Service 5: payment-requester
        - uses: kustomize-set-image
          as: update-payment-requester
          config:
            path: repo/environments/dev/payment-requester
            images:
              - image: ${{ vars.registry }}/traces-test-payment-requester
                newTag: ${{ image(vars.registry + '/traces-test-payment-requester').tag }}

        - uses: git-commit
          as: commit
          config:
            path: repo
            message: |
              Promote to dev
              ${{ outputs['update-account-service'].commitMessage }}

        - uses: git-push
          config:
            path: repo
            branch: ${{ vars.branch }}
