apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: traces-test
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: traces-test-warehouse
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/tijnsemmekrot/traces-test.git
            checkout:
              - branch: kargo-implementation
                path: repo

        # Service 1
        - uses: kustomize-set-image
          config:
            path: repo/environments/dev/account-service
            images:
              - image: 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/traces-test-account-service
                # Access via the Warehouse key
                newTag: ${{ vars.warehouses['traces-test-warehouse'].images['account-service-image'].tag }}

        # Service 2
        - uses: kustomize-set-image
          config:
            path: repo/environments/dev/fraud-detector
            images:
              - image: 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/traces-test-fraud-detector
                newTag: ${{ vars.warehouses['traces-test-warehouse'].images['fraud-detector-image'].tag }}

        # Service 3
        - uses: kustomize-set-image
          config:
            path: repo/environments/dev/notification-service
            images:
              - image: 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/traces-test-notification-service
                newTag: ${{ vars.warehouses['traces-test-warehouse'].images['notification-service-image'].tag }}

        # Service 4
        - uses: kustomize-set-image
          config:
            path: repo/environments/dev/payment-processor
            images:
              - image: 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/traces-test-payment-processor
                newTag: ${{ vars.warehouses['traces-test-warehouse'].images['payment-processor-image'].tag }}

        # Service 5
        - uses: kustomize-set-image
          config:
            path: repo/environments/dev/payment-requester
            images:
              - image: 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/traces-test-payment-requester
                newTag: ${{ vars.warehouses['traces-test-warehouse'].images['payment-requester-image'].tag }}

        - uses: git-commit
          config:
            path: repo
            messageFromSteps:
              - step-2
              - step-3
              - step-4
              - step-5
              - step-6

        - uses: git-push
          config:
            path: repo
            targetBranch: kargo-implementation
