# kargo/warehouse.yaml
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: traces-test-warehouse
  namespace: traces-test
spec:
  subscriptions:
    - image:
        name: account-service-image
        repoURL: index.docker.io/tijnsemmekrot/traces-test-account-service
        imagePullSecrets: [{ name: dockerhub-creds }]
        imageSelectionStrategy: Lexical
        strictSemvers: false
    - image:
        name: fraud-detector-image
        repoURL: index.docker.io/tijnsemmekrot/traces-test-fraud-detector
        imagePullSecrets: [{ name: dockerhub-creds }]
        imageSelectionStrategy: Lexical
        strictSemvers: false
    - image:
        name: notification-service-image
        repoURL: index.docker.io/tijnsemmekrot/traces-test-notification-service
        imagePullSecrets: [{ name: dockerhub-creds }]
        imageSelectionStrategy: Lexical
        strictSemvers: false
    - image:
        name: payment-processor-image
        repoURL: index.docker.io/tijnsemmekrot/traces-test-payment-processor
        imagePullSecrets: [{ name: dockerhub-creds }]
        imageSelectionStrategy: Lexical
        strictSemvers: false
    - image:
        name: payment-requester-image
        repoURL: index.docker.io/tijnsemmekrot/traces-test-payment-requester
        imagePullSecrets: [{ name: dockerhub-creds }]
        imageSelectionStrategy: Lexical
        strictSemvers: false
