apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elastic-agent-staging

resources:
  - ../../base

# Staging-specific image tag (promoted from dev by Kargo)
images:
  - name: docker.elastic.co/beats/elastic-agent
    newName: 000000000000.dkr.ecr.us-east-1.amazonaws.com/elastic-agent
    newTag: 8.12.0 # Kargo will update this

patchesStrategicMerge:
  - values-overlay.yaml

commonLabels:
  environment: staging
