apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fraud-detector
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tijnsemmekrot/traces-test.git
    targetRevision: HEAD
    path: environments/dev/fraud-detector
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
