apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-requester
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:tijnsemmekrot/traces-test.git
    targetRevision: HEAD
    path: apps/payment-requester
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
