apiVersion: v1
kind: Namespace
metadata:
  name: elastic-agent-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-agent-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-agent-prod
