---
apiVersion: v1
kind: Namespace
metadata:
  name: elastic-agent-kargo
  labels:
    kargo.akuity.io/project: "true"

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: elastic-agent-kargo

---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: elastic-agent
  namespace: elastic-agent-kargo
spec:
  subscriptions:
    - image:
        repoURL: 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/elastic-agent
        allowInsecure: true
        semverConstraint: ">=8.12.0"
        discoveryLimit: 5
        imageSelectionStrategy: NewestBuild

---
# Dev Stage
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: elastic-agent-kargo
spec:
  requestedFreight:
    - origin: { kind: Warehouse, name: elastic-agent }
      sources: { direct: true }
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: git@github.com:tijnsemmekrot/traces-test.git
            checkout: [{ branch: kargo-implementation, path: ./src }]
        - uses: kustomize-set-image
          as: update-image
          config:
            path: ./src/elastic-agent/environments/dev
            images:
              - image: 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/elastic-agent
                tag: ${{ imageFrom("000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/elastic-agent").Tag }}
        - uses: git-commit
          as: commit
          config:
            path: ./src
            message: "feat(dev): update image to ${{ imageFrom('000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/elastic-agent').Tag }}"
        - uses: git-push
          config:
            path: ./src
            targetBranch: kargo-implementation
        - uses: argocd-update
          config:
            apps: [{ name: elastic-agent-dev, namespace: argocd }]

---
# Staging Stage
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: elastic-agent-kargo
spec:
  requestedFreight:
    - origin: { kind: Warehouse, name: elastic-agent }
      sources: { stages: [dev] }
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: git@github.com:tijnsemmekrot/traces-test.git
            checkout: [{ branch: kargo-implementation, path: ./src }]
        - uses: kustomize-set-image
          as: update-image
          config:
            path: ./src/elastic-agent/environments/staging
            images:
              - image: 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/elastic-agent
                tag: ${{ imageFrom("000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/elastic-agent").Tag }}
        - uses: git-commit
          as: commit
          config:
            path: ./src
            message: "feat(staging): update image to ${{ imageFrom('000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/elastic-agent').Tag }}"
        - uses: git-push
          config:
            path: ./src
            targetBranch: kargo-implementation
        - uses: argocd-update
          config:
            apps: [{ name: elastic-agent-staging, namespace: argocd }]

---
# Prod Stage
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: elastic-agent-kargo
spec:
  requestedFreight:
    - origin: { kind: Warehouse, name: elastic-agent }
      sources: { stages: [staging] }
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: git@github.com:tijnsemmekrot/traces-test.git
            checkout: [{ branch: kargo-implementation, path: ./src }]
        - uses: kustomize-set-image
          as: update-image
          config:
            path: ./src/elastic-agent/environments/prod
            images:
              - image: 000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/elastic-agent
                tag: ${{ imageFrom("000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/elastic-agent").Tag }}
        - uses: git-commit
          as: commit
          config:
            path: ./src
            message: "feat(prod): update image to ${{ imageFrom('000000000000.dkr.ecr.eu-west-1.localhost.localstack.cloud:4566/elastic-agent').Tag }}"
        - uses: git-push
          config:
            path: ./src
            targetBranch: kargo-implementation
        - uses: argocd-update
          config:
            apps: [{ name: elastic-agent-prod, namespace: argocd }]
